Models/ApartEkle.cs
using System.ComponentModel.DataAnnotations;

namespace ApartDeneme.Models
{
	public class ApartEkle
	{
		//TODO Apart bilgilerini kayıtı için model olusturulup gelen degerleri ApartControllerde islmeleri saglandı
		[Key]
		public int id { get; set; }
		public string il { get; set; }
		public string ilce { get; set; }
		public string Adres { get; set; }
		public int odasayısı { get; set; }
		public double metreKare { get; set; }
		public string fotograf { get; set; }
		public int fiyat { get; set; }


	}
}

Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace ApartDeneme.Models
{
	public class Context:DbContext
	{ //TODO Veri tabanı bağlantısı oluşturuldu manager consoleden migration komutları calitrilip migration olusturuldu
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer("server=DESKTOP-4ALBNKR; database=apartdeneme1; integrated security=true; TrustServerCertificate = True;");
		}
		public DbSet<ApartEkle> aparts { get; set; }

		public DbSet<Giris> girises { get; set; }
		public DbSet<KullaniciKayit> kullanicikayit { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace ApartDeneme.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Giris.cs
using System.ComponentModel.DataAnnotations;

namespace ApartDeneme.Models
{
	public class Giris
	{
		//TODO  Giris.cshtml bilgileri için model olusturulup gelen degerleri ApartControllerde islmeleri saglandı
		[Key]
		public int id { get; set; }
		public string kullaniciAdi { get; set; }
		public string sifre { get; set; }
	}
}

Models/KullaniciKayit.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace ApartDeneme.Models
{
	public class KullaniciKayit
	{
		//TODO Kayit.cshtml dosyası için model olusturulup gelen degerleri ApartControllerde islmeleri saglandı
		[Key]
		public int id { get; set; }
		public string isim { get; set; }
		public string soyisim { get; set; }
		public string cinsiyet { get; set; }
		public string kullaniciAdi { get; set; }
		public string parola { get; set; }

	}
}

Models/iletisim.cs
using System.Reflection.Metadata.Ecma335;

namespace ApartDeneme.Models
{
    public class iletisim
    {
        public string Ad { get; set; }
        public string email { get; set; }
        public string sikayet { get; set; }
    }
}

Controllers/ApartController.cs
using ApartDeneme.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Security.Claims;

namespace ApartDeneme.Controllers
{
	public class ApartController : Controller
	{
		Context dbs = new Context();
		public ActionResult Anasayfa()
		{
			return View();
		}

		public IActionResult ApartEkle()
		{
			return View();

		}
		[HttpPost]
		public IActionResult ApartEkle(ApartEkle ekle)
		{
			dbs.aparts.Add(ekle);
			dbs.SaveChanges();
			return RedirectToAction("Anasayfa");

		}
		public IActionResult Kayit()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Kayit(KullaniciKayit kayit)
		{
			dbs.kullanicikayit.Add(kayit);
			dbs.SaveChanges();
			return RedirectToAction("Giris");
		}
		
		[HttpGet]
		public IActionResult Giris()
		{
			return View();
		}
		//[Authorize]
		//public async Task <IActionResult> Giris(Giris g)
		//{
		//	var bilgiler = dbs.girises.FirstOrDefault(x => x.kullaniciAdi == g.kullaniciAdi && x.sifre == g.sifre);
		//	if (bilgiler!=null)
		//	{
		//		var claims = new List<Claim>
		//		{
		//			new Claim(ClaimTypes.Name,g.kullaniciAdi)
		//		};
		//		var useridentity=new ClaimsIdentity(claims,"Giris");
		//		ClaimsPrincipal principal= new ClaimsPrincipal(useridentity);
		//		await HttpContext.SignInAsync(principal);
		//		return RedirectToAction("Apartlar");
		//	}

		//	return View();

		//}
		public IActionResult Apartlar()
		{
			var degerler = dbs.aparts.ToList();

			return View(degerler);
		}
		public IActionResult ApartSil(int id)
		{
			var del = dbs.aparts.Find(id);
			dbs.aparts.Remove(del);
			dbs.SaveChanges();
			return RedirectToAction("Apartlar");
		}
		public IActionResult ApartBilgileriGetir(int id)
		{
			var apartbilgi = dbs.aparts.Find(id);
			return View("ApartBilgileriGetir",apartbilgi);


		}


		public IActionResult Guncelle(ApartEkle duzenle)
		{
			var gnc = dbs.aparts.Find(duzenle.id);
			gnc.Adres = duzenle.Adres;
			dbs.SaveChanges();
			return RedirectToAction("ApartEkle");
		}
		public IActionResult Yıllık()
		{
			var degerler = dbs.aparts.ToList();

			return View(degerler);
		}
	}
}

Controllers/HomeController.cs
using ApartDeneme.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ApartDeneme.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/IletisimController.cs
using ApartDeneme.Models;
using Microsoft.AspNetCore.Mvc;

namespace ApartDeneme.Controllers
{
	public class IletisimController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		[HttpGet]
		public IActionResult iletişim()
		{
			return View();
		}
		[HttpPost]
		public IActionResult iletişim(iletisim ilet)
		{
			if (ModelState.IsValid)
			{
				var messages=ModelState.ToList();
				return View(ilet);
			}
			return View();
		}
	}
}

Controllers/SayfalarController.cs
using Microsoft.AspNetCore.Mvc;

namespace ApartDeneme.Controllers
{
	public class SayfalarController : Controller
	{
		public IActionResult Hakkimizda()
		{
			return View();
		}
		public IActionResult Haberler()
		{
			return View();
		}
		public IActionResult Iletisim()
		{
			return View();
		}
		public IActionResult Destek()
		{
			return View();
		}
	}
}

Views/Apart/Anasayfa.cshtml
@{
	ViewData["Title"] = "Anasayfa";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/anasayfa.css" rel="stylesheet" />

<!DOCTYPE html>
<html>
<head>
	<title>ApartEv.com</title>


</head>

<body >
	<div class="kutu">
		<a href="/Apart/Yıllık" class="btn btn-dark" style="background-color:cornflowerblue " >Yıllık</a>
	</div><div class="kutu">
		<a href="/Apart/Yıllık" class="btn btn-dark" style="background-color:brown">Aylık</a>
	</div><div class="kutu">
		<a href="/Apart/Yıllık" class="btn btn-dark" style="background-color:cadetblue">Günlük</a>
	</div>
	
	

</body>

</html>

Views/Apart/ApartBilgileriGetir.cshtml
@model ApartDeneme.Models.ApartEkle
@{
	ViewData["Title"] = "ApartBilgileriGetir";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Html Helper form metotoları kullanımı ornegi*@

@using (Html.BeginForm("Guncelle", "Apart", FormMethod.Post))
{

	<b>İL</b>

	@Html.TextBoxFor(x=>x.il,new{@class="form-control"})
	<br />
	<b>İLCE</b>

	@Html.TextBoxFor(x=>x.ilce,new{@class="form-control"})
	<br />
	<b>ADRES</b>

	@Html.TextBoxFor(x=>x.Adres,new{@class="form-control"})
	<br />
	<b>ODA SAYISI</b>

	@Html.TextBoxFor(x=>x.odasayısı,new{@class="form-control"})
	<br />
	<b>METREKARE</b>

	@Html.TextBoxFor(x=>x.metreKare,new{@class="form-control"})
	<br />
	<b>FOTOĞRAF</b>

	@Html.TextBoxFor(x=>x.fotograf,new{@class="form-control"})
	<br />

	<b>FİYAT</b>

	@Html.TextBoxFor(x=>x.fiyat,new{@class="form-control"})
	<br />


	<button class="btn btn-info" style="background-color:blueviolet">Guncelle</button>
}

Views/Apart/ApartEkle.cshtml
@model ApartDeneme.Models.ApartEkle
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "ApartEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Tag Helper kullanimi*@
<h2>
	@DateTime.Now
</h2>

@*Html Helper kullanımı*@
<form class="form-group" method="post">
	@Html.LabelFor(x=>x.il)
	@Html.TextBoxFor(x=>x.il,new{@class="form-control"})

	@Html.LabelFor(x=>x.ilce)
	@Html.TextBoxFor(x=>x.ilce,new{@class="form-control"})

	@Html.LabelFor(x=>x.Adres)
	@Html.TextBoxFor(x=>x.Adres,new{@class="form-control"})

	@Html.LabelFor(x=>x.odasayısı)
	@Html.TextBoxFor(x=>x.odasayısı,new{@class="form-control"})

	@Html.LabelFor(x=>x.metreKare)
	@Html.TextBoxFor(x=>x.metreKare,new{@class="form-control"})

	@Html.LabelFor(x=>x.fotograf)
	@Html.TextBoxFor(x=>x.fotograf,new{@class="form-control"})

	@Html.LabelFor(x=>x.fiyat)
	@Html.TextBoxFor(x=>x.fiyat,new{@class="form-control"})


	<br />
	<button class ="btn btn-info">Ekle</button>
	<a href="/Apart/Apartlar" class="btn btn-dark">Apartlarım</a> 
</form>

Views/Apart/Apartlar.cshtml
@using ApartDeneme.Models
@model List<ApartEkle>
@{
	ViewData["Title"] = "Yıllık";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yıllık Apartlar</h1>


<table class="table table-bordered">
	<tr>
		<th>il</th>
		<th>ilçe</th>
		<th>metrekare</th>
		<th>odasayisi</th>
		<th>odasayisifiyat</th>
	</tr>
	@foreach (var apartset in Model)
	{
			<tr>
				<td>@apartset.il</td>
				<td>@apartset.ilce</td>
				<td>@apartset.metreKare</td>
				<td>@apartset.odasayısı</td>
				<td>@apartset.fiyat</td>
			<td><a href="/Apart/ApartBilgileriGetir/@apartset.id" class="btn btn-dark" style="background-color:aquamarine">Güncelle</a>	</td>
			<td><a href ="/Apart/ApartSil/@apartset.id" class="btn btn-dark" style="background-color:aquamarine">Sil</a>	</td>
			
			</tr>
	}
	
</table>

Views/Apart/Giris.cshtml
@model ApartDeneme.Models.Giris
@{
    ViewData["Title"] = "Giris";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-group" method="post">
	@Html.LabelFor(x=>x.kullaniciAdi)
	@Html.TextBoxFor(x=>x.kullaniciAdi,new{@class="form-control"})
	<br />
	@Html.LabelFor(x=>x.sifre)
	@Html.TextBoxFor(x=>x.sifre,new{@class="form-control"})
	<br />
	@*<input type="submit" value="Giriş" />*@
</form>
<a href="/Apart/ApartEkle" class="btn btn-dark">Giriş</a>

Views/Apart/Kayit.cshtml
@model ApartDeneme.Models.KullaniciKayit
@{
    ViewData["Title"] = "Kayit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form class="form-group" method="post">
	<a>İsim</a>
	@Html.TextBoxFor(x=>x.isim,new{@class="form-control"})
	<a>Soyisim</a>
	@Html.TextBoxFor(x=>x.soyisim,new{@class="form-control"})
	<a>Cinsiyet</a>
	@Html.TextBoxFor(x=>x.cinsiyet,new{@class="form-control"})
	<a>Kullanici Adi</a>
	@Html.TextBoxFor(x=>x.kullaniciAdi,new{@class="form-control"})
	<a>Parola</a>
	@Html.TextBoxFor(x=>x.parola,new{@class="form-control"})
	<br />
	<button class="btn btn-dark">Kayit</button>

</form>

Views/Apart/Yıllık.cshtml
@using ApartDeneme.Models
@model List<ApartEkle>
@{
	ViewData["Title"] = "Yıllık";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yıllık Apartlar</h1>
<link href="~/css/apartkutu.css" rel="stylesheet" />



@foreach (var apartset in Model)
{
	<div class="kutu">
		@*<div class="foto">
			<img src=@apartset.fotograf />
		</div>*@
		
		<a>İl:@apartset.il</a>
		<a>ilçe:@apartset.ilce</a>
		<a>Metrekare:@apartset.metreKare</a>
		<a>Oda sayısı:@apartset.odasayısı</a>
		<a>Fiyat:@apartset.fiyat</a>		
		
	</div>


}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Iletisim/iletişim.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@model ApartDeneme.Models.iletisim
<script src="d:\programcalismalari\programmin works\asp.net\works\apartdeneme\wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js"></script>
@{
    Layout = null;
}

<form asp-action="iletişim" asp-controller="Iletisim" method="post">
    <input type="text" asp-for="Ad"  placeholder="İsim" />
    <span asp-validation-for="Ad"></span><br />
    <input type="text" asp-for="email"  placeholder="Email" />
    <span asp-validation-for="email"></span><br />
    <input type="text" asp-for="sikayet"  placeholder="Sikayet" />
    <span asp-validation-for="sikayet"></span><br />


</form>

Views/Sayfalar/Destek.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *,ApartDeneme


<email  a="abc" mail="apartevim10@gmail.com" display="Apart ev maili"></email>

Views/Sayfalar/Haberler.cshtml
@{
    ViewData["Title"] = "Haberler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Haberler</h1>

<h1>Haberler</h1>

<h1>Haberler</h1>

<h1>Haberler</h1>
<h1>Haberler</h1>

Views/Sayfalar/Hakkimizda.cshtml
@{
    ViewData["Title"] = "Hakkimizda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Hakkimizda</h1>

<h4>nclalksmacnıp</h4>
<h4>nclalksmacnıp</h4>
<h4>nclalksmacnıp</h4>
<h4>nclalksmacnıp</h4>
<h4>nclalksmacnıp</h4>
<h4>nclalksmacnıp</h4>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ApartDeneme</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ApartDeneme.styles.css" asp-append-version="true" />
	<link href="~/css/footer.css" rel="stylesheet" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Apart" asp-action="Anasayfa">Anasayfa</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Sayfalar" asp-action="Hakkimizda">Hakkimizda</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Sayfalar" asp-action="Haberler">Haberler</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Sayfalar" asp-action="Iletisim">İletişim</a>
						</li>						
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Sayfalar" asp-action="Destek">Destek</a>
						</li>				   
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Apart" asp-action="Kayit">Kayit</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Apart" asp-action="Giris">Giriş</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="footer" style="background-color:aquamarine">	
		<h4>Bizi tercih ettiğiniz için teşekkür ederiz.</h4>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>